# NumPy Assignment  
**Submitter Name:** Aasif Majeed  
**Date:** 24 Jan 2023  


Each problem contains:
- The **question statement** (with question number)
- A clear **explanation**
- **Python/NumPy code** (where applicable) + short outputs


In [1]:
import numpy as np
np.set_printoptions(suppress=True)  # cleaner printing


We will reuse the following array in multiple questions:

\[
A =
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}
\]


In [2]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Question 1

### Question
What is a Python library? Why do we use Python libraries?

### Explanation
A **Python library** is a collection of pre-written code (modules, functions, classes) that helps you perform common tasks without writing everything from scratch.

**Why we use libraries:**
- **Saves time**: reuse proven implementations
- **Reliability**: tested and optimized by the community
- **Productivity**: focus on solving the problem, not reinventing tools
- **Performance**: libraries like NumPy use optimized C/Fortran under the hood

Examples: `numpy` for arrays, `pandas` for tables, `matplotlib` for plotting.


## Question 2

### Question
What is the difference between NumPy array and List?

### Explanation
Key differences:

1. **Type consistency**
   - Python list can store mixed types (int, float, string together)
   - NumPy array is usually a **single data type** for speed and memory efficiency

2. **Speed**
   - NumPy operations are vectorized and run in optimized compiled code → **faster**

3. **Memory**
   - NumPy arrays use contiguous memory blocks (efficient)
   - Lists store references to objects (more overhead)

4. **Math operations**
   - Lists: `a + b` concatenates
   - NumPy arrays: `a + b` does element-wise addition


In [3]:
lst = [1,2,3]
arr = np.array([1,2,3])

print("List + List:", lst + lst)     # concatenation
print("Array + Array:", arr + arr)  # element-wise


List + List: [1, 2, 3, 1, 2, 3]
Array + Array: [2 4 6]


## Question 3

### Question
Find the shape, size and dimension of the following array:

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

### Explanation
- **shape**: (rows, columns)  
- **size**: total number of elements  
- **ndim**: number of dimensions (2 for a matrix)


In [4]:
print("Array:\n", A)
print("Shape:", A.shape)   # (3, 4)
print("Size :", A.size)    # 12
print("ndim :", A.ndim)    # 2


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Size : 12
ndim : 2


## Question 4

### Question
Write python code to access the first row of the following array.

### Explanation
In NumPy, row indexing is 0-based.
- First row is row index `0` → `A[0]`


In [5]:
first_row = A[0]
print("First row:", first_row)


First row: [1 2 3 4]


## Question 5

### Question
How do you access the element at the third row and fourth column from the given numpy array?

### Explanation
In NumPy indexing is 0-based:
- Third row → index `2`
- Fourth column → index `3`
So the element is `A[2, 3]`.


In [6]:
element = A[2, 3]
print("Element at 3rd row, 4th col:", element)


Element at 3rd row, 4th col: 12


## Question 6

### Question
Write code to extract all odd-indexed elements from the given numpy array.

### Explanation
Interpretation: with **0-based indexing**, odd indices are 1,3,5,...  
A common meaning is **odd indices in the flattened array**.

Steps:
1. Flatten array to 1D: `A.flatten()`
2. Take elements at odd indices: `[1::2]`


In [7]:
flat = A.flatten()
odd_indexed = flat[1::2]
print("Flattened A:", flat)
print("Odd-indexed elements (1,3,5,...):", odd_indexed)


Flattened A: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Odd-indexed elements (1,3,5,...): [ 2  4  6  8 10 12]


## Question 7

### Question
How can you generate a random 3x3 matrix with values between 0 and 1?

### Explanation
Use `np.random.rand(3,3)` which draws from a uniform distribution over [0, 1).


In [8]:
rand_mat = np.random.rand(3,3)
rand_mat


array([[0.56869051, 0.71618089, 0.96834348],
       [0.78903961, 0.51128482, 0.27491791],
       [0.19138908, 0.95998365, 0.36802976]])

## Question 8

### Question
Describe the difference between `np.random.rand` and `np.random.randn`.

### Explanation
- `np.random.rand(d0, d1, ...)`  
  Samples from a **uniform distribution** on **[0, 1)**.

- `np.random.randn(d0, d1, ...)`  
  Samples from a **standard normal (Gaussian) distribution** with:
  - mean = 0
  - standard deviation = 1
  Values can be negative or > 1.

So: **rand = uniform**, **randn = normal**.


In [9]:
u = np.random.rand(5)
g = np.random.randn(5)
print("rand  (uniform [0,1)):", u)
print("randn (normal mean0 std1):", g)


rand  (uniform [0,1)): [0.18017727 0.99834906 0.81268315 0.78745843 0.45169049]
randn (normal mean0 std1): [ 0.62712016  0.7725442   0.7090954  -0.83771028  0.05399559]


## Question 9

### Question
Write code to increase the dimension of the following array.

### Explanation
To increase dimension, we add a new axis using:
- `np.expand_dims(A, axis=0)`  → shape becomes (1, 3, 4)
- `np.expand_dims(A, axis=-1)` → shape becomes (3, 4, 1)

This is often needed for broadcasting, ML batches, or image-like data.


In [10]:
A0 = np.expand_dims(A, axis=0)
A_last = np.expand_dims(A, axis=-1)

print("Original shape:", A.shape)
print("Add axis=0 shape:", A0.shape)
print("Add axis=-1 shape:", A_last.shape)


Original shape: (3, 4)
Add axis=0 shape: (1, 3, 4)
Add axis=-1 shape: (3, 4, 1)


## Question 10

### Question
How to transpose the following array in NumPy?

### Explanation
Transpose swaps rows and columns:
- `A.T` or `np.transpose(A)`


In [11]:
print("A:\n", A)
print("A.T:\n", A.T)


A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A.T:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## Question 11

### Question
Consider the following matrices:
- Matrix A: [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
- Matrix B: [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

Perform:
1) Index-wise multiplication  
2) Matrix multiplication  
3) Add both matrices  
4) Subtract matrix B from A  
5) Divide Matrix B by A

### Explanation
Let `A` and `B` be NumPy arrays.

1) **Index-wise multiplication** means **element-wise** multiplication: `A * B`  
2) **Matrix multiplication** means dot-product multiplication: `A @ B`  
   - Note: For matrix multiplication, inner dimensions must match.
   - A is (3×4). To multiply with B, B must be (4×something).  
   - Since B here is also (3×4), **A @ B is not valid**.
   - We can demonstrate valid multiplication using `A @ B.T` which is (3×4) @ (4×3) = (3×3).
3) Addition: `A + B`  
4) Subtraction: `A - B`  
5) Division: `B / A` (element-wise)


In [12]:
B = A.copy()

# 1) Element-wise multiplication
elem_mul = A * B

# 2) Matrix multiplication (valid example using B.T)
mat_mul = A @ B.T   # (3x4) @ (4x3) = (3x3)

# 3) Add
addAB = A + B

# 4) Subtract B from A
subAB = A - B

# 5) Divide B by A (element-wise)
divBA = B / A

print("1) Element-wise A*B:\n", elem_mul)
print("\n2) Matrix multiplication A @ B.T:\n", mat_mul)
print("\n3) A + B:\n", addAB)
print("\n4) A - B:\n", subAB)
print("\n5) B / A:\n", divBA)


1) Element-wise A*B:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2) Matrix multiplication A @ B.T:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3) A + B:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4) A - B:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5) B / A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Question 12

### Question
Which function in NumPy can be used to swap the byte order of an array?

### Explanation
You can use:
- `arr.byteswap()` (or `arr.byteswap(inplace=True)`) to swap byte order.
- Often paired with `arr.newbyteorder()` to interpret data correctly after swapping.

This is useful when reading binary data created on systems with different endianness (big-endian vs little-endian).


In [13]:
x = np.array([1, 256], dtype=np.int16)
print("Original:", x, x.dtype)

swapped = x.byteswap().newbyteorder()
print("Byteswapped + newbyteorder:", swapped, swapped.dtype)


Original: [  1 256] int16
Byteswapped + newbyteorder: [  1 256] >i2


## Question 13

### Question
What is the significance of the `np.linalg.inv` function?

### Explanation
`np.linalg.inv(A)` computes the **inverse** of a square matrix `A` (if it exists).

- If `A` is invertible, then: `A @ inv(A) = I` (identity matrix).
- Inversion is used in solving linear systems and algebraic manipulation.

Important notes:
- `A` must be **square** (n×n).
- `A` must be **non-singular** (determinant ≠ 0).
- In practice, solving `Ax=b` is usually better done with `np.linalg.solve(A, b)` than explicitly inverting.


In [14]:
M = np.array([[2., 1.],
              [5., 3.]])
Minv = np.linalg.inv(M)
I = M @ Minv
print("M:\n", M)
print("inv(M):\n", Minv)
print("M @ inv(M) ≈ I:\n", I)


M:
 [[2. 1.]
 [5. 3.]]
inv(M):
 [[ 3. -1.]
 [-5.  2.]]
M @ inv(M) ≈ I:
 [[1. 0.]
 [0. 1.]]


## Question 14

### Question
What does the `np.reshape` function do, and how is it used?

### Explanation
`np.reshape` changes the **shape** of an array **without changing its data** (same elements, new dimensions).

Rules:
- Total number of elements must stay the same.
- You can use `-1` to let NumPy infer one dimension automatically.

Example: reshape a (3×4) array into (2×6) or (12,) 1D array.


In [15]:
print("A shape:", A.shape)

A_1d = A.reshape(-1)     # (12,)
A_2x6 = A.reshape(2, 6)  # (2,6)

print("Reshape to 1D:", A_1d, "shape:", A_1d.shape)
print("Reshape to 2x6:\n", A_2x6, "shape:", A_2x6.shape)


A shape: (3, 4)
Reshape to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12] shape: (12,)
Reshape to 2x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] shape: (2, 6)


## Question 15

### Question
What is broadcasting in NumPy?

### Explanation
**Broadcasting** is a NumPy feature that allows arrays with different shapes to be combined in arithmetic operations.

NumPy automatically “stretches” the smaller array along dimensions of size 1 (without copying data) if shapes are compatible.

Broadcasting rules (simplified):
- Compare shapes from the rightmost dimension.
- Two dimensions are compatible if they are equal, or one of them is 1.

Example:
- (3×4) array + (4,) vector → vector is broadcast across rows.


In [16]:
v = np.array([10, 20, 30, 40])  # shape (4,)
print("A shape:", A.shape)
print("v shape:", v.shape)

A_plus_v = A + v  # v broadcast to each row
print("A + v:\n", A_plus_v)


A shape: (3, 4)
v shape: (4,)
A + v:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
